on:
  release:
    types: [published]
    
# Zips the profile and uploads to the Vatpac AWS server
name: Publish Profile
jobs:
  zip-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Archive Release
      uses: thedoctor0/zip-release@master
      with:
        filename: 'profile.zip'
        exclusions: '*.git* /*node_modules/* .editorconfig *.md'
    - name: S3-Deploy-Action
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --follow-symlinks --delete
      env:
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: 'ap-southeast-2' 
        DEST_DIR: 'vatsys/pacific'
